### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by ulikoehler** [mabl/ChibiOS#7]
For about two weeks the repository has not been updated from SVN. Is there any way to fix that?

Thanks!

**Comment by mabl** [comment]
Thanks, I'll look into that over the weekend.

**Comment by ulikoehler** [comment]
Seems to be working now. Thanks!

**Comment by mabl** [comment]
The SVN repository got corrupted during the SF downtime. I had to go back several revisions and force an update. Not the nicest thing to do, but this is what happens if you use SVN.

**Comment by ulikoehler** [comment]
Fully agreed ;-) Exactly the reason why I use git. Thanks by the way for setting up this mirror which helps me nearly every day!
